/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Module-order"
 * 	found in "Communications.asn"
 */

#ifndef	_Location_H_
#define	_Location_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Location */
typedef struct Location {
	long	 latitude;
	long	 longitude;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Location_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Location;

#ifdef __cplusplus
}
#endif

#endif	/* _Location_H_ */
#include "asn_internal.h"
