/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Module-order"
 * 	found in "Communications.asn"
 */

#ifndef	_Message_H_
#define	_Message_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Request.h"
#include "Response.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Message_PR {
	Message_PR_NOTHING,	/* No components present */
	Message_PR_request,
	Message_PR_response,
	/* Extensions may appear below */
	
} Message_PR;

/* Message */
typedef struct Message {
	Message_PR present;
	union Message_u {
		Request_t	 request;
		Response_t	 response;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Message;

#ifdef __cplusplus
}
#endif

#endif	/* _Message_H_ */
#include "asn_internal.h"
