/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Module-order"
 * 	found in "Communications.asn"
 */

#ifndef	_Response_H_
#define	_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include "System-health.h"
#include "Location.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Response */
typedef struct Response {
	System_health_t	 health;
	Location_t	 location;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _Response_H_ */
#include <asn_internal.h>
