/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "Module-order"
 * 	found in "Communications.asn"
 */

#ifndef	_System_health_H_
#define	_System_health_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum System_health {
	System_health_nominal	= 0
	/*
	 * Enumeration is extensible
	 */
} e_System_health;

/* System-health */
typedef long	 System_health_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_System_health;
asn_struct_free_f System_health_free;
asn_struct_print_f System_health_print;
asn_constr_check_f System_health_constraint;
ber_type_decoder_f System_health_decode_ber;
der_type_encoder_f System_health_encode_der;
xer_type_decoder_f System_health_decode_xer;
xer_type_encoder_f System_health_encode_xer;
per_type_decoder_f System_health_decode_uper;
per_type_encoder_f System_health_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _System_health_H_ */
#include "asn_internal.h"
